SRCS = \
FFTImplementationCallback.cpp \
cosineTaper.cpp \
estimateGustIntensity.cpp \
fftfunc.cpp \
getAutoSpectra.cpp \
getGustMdlParams.cpp \
getMeasuredDataFft.cpp \
getSysGustMdlFreqResp.cpp \
integrateMdl.cpp \
interp1.cpp \
psdft.cpp \
removeInputsFromMeasFft.cpp \
repmat.cpp \
rtGetInf.cpp \
rtGetNaN.cpp \
rt_nonfinite.cpp \
setFreqLimits.cpp \
steponce_data.cpp \
steponce_rtwutil.cpp \
streamClass.cpp \
sum.cpp \
svd.cpp \
trapz.cpp \
xaxpy.cpp \
xnrm2.cpp \
xrot.cpp \
xrotg.cpp \
xswap.cpp \
streamClassWrap.cpp 
